name: Run Bugspots on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bugspots-analysis:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Ruby and bugspots gem
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install bugspots gem
        run: gem install bugspots

      # Ensure .gitignore includes bugspots-work-*
      - name: Update .gitignore
        run: |
          echo "bugspots-work-*" >> .gitignore
          git add .gitignore
          git commit -m "Update .gitignore to exclude bugspots-work-*" || echo "No changes to .gitignore"

      # Run the Bugspots script
      - name: Run Bugspots script
        run: |
          chmod +x bugspots.sh
          ./run-bugspots-against-remote.sh

      # Commit the generated log files
      - name: Commit Bugspots results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add bugspots-results/
          git commit -m "Add Bugspots analysis results for PR #$GITHUB_EVENT_NUMBER" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
