name: Run Bugspots Script

on:
  push:
    branches:
      - master  # or main, depending on your default branch
  pull_request:
    branches:
      - master  # or main, depending on your default branch

jobs:
  run-bugspots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: OpenElements/hiero-enterprise-java  # Specify the target repository
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target-repo  # Check out the repository into a subdirectory

      - name: Checkout BugPredict Repository
        uses: actions/checkout@v3
        with:
          repository: Ndacyayisenga-droid/BugPredict
          token: ${{ secrets.GITHUB_TOKEN }}
          path: BugPredict  # Check out BugPredict into a separate directory

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bugspots Dependencies
        run: |
          gem install bugspots
          gem install rainbow
          gem install mongo

      - name: Run Bugspots Script
        working-directory: BugPredict/BugSpots/bin
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          ruby bugspots -b main -d 100 -w "fixes,closed" ../../target-repo
