name: Run Bugspots Script

on:
  push:
    branches:
      - master  # or main
  pull_request:
    branches:
      - master  # or main

jobs:
  run-bugspots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: OpenElements/hiero-enterprise-java
          token: ${{ secrets.GITHUB_TOKEN }}
          # No 'path' specified, clones to root

      - name: Checkout BugPredict Repository
        uses: actions/checkout@v3
        with:
          repository: Ndacyayisenga-droid/BugPredict
          token: ${{ secrets.GITHUB_TOKEN }}
          path: BugPredict

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bugspots Dependencies
        run: |
          gem install bugspots
          gem install rainbow
          gem install mongo

      # - name: Clone Hiero Enterprise Java Repository
      #   run: |
      #     git clone https://github.com/OpenElements/hiero-enterprise-java.git .

      - name: Run Bugspots Script
        working-directory: .
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          ruby BugPredict/BugSpots/bin/bugspots -b main ./OpenElements/hiero-enterprise-java